server.port=8010
product-catalogue-uri=${PRODUCT_CATALOGUE_URI:http://productcatalogue:8020}
stock-manager-uri=${STOCK_MANAGER_URI:http://stockmanager:8030}
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
