apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shopfront
  namespace: djshopping
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shopfront
                port:
                  name: http
