server.port=8030
spring.datasource.url=jdbc:h2:mem:stockdb;DB_CLOSE_DELAY=-1
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=false
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
